### ISSUE TITLE
Compiler error: storage size of weaponQAV isn't known

### ISSUE THREAD

**Issue by lemming104** [nukeykt/NBlood#225]
Compiling with GCC 9.x (MSYS2):

in file included from source/blood/src/blood.cpp:68:
source/blood/src/weapon.h:31:6: error: storage size of 'weaponQAV' isn't known
   31 | QAV* weaponQAV[];

Seems to have been introduced by commit bc3473390b73e43c373b4e38100bc3e955f0affb

Still builds fine in VS 2019.  Go figure.

**Comment by CommonLoon102** [comment]
fixed, you can close

**Comment by lemming104** [comment]
Yup, seems to build in MSYS2 again now.
