### ISSUE TITLE
can't compile master on Ubuntu

### ISSUE THREAD

**Issue by LiamDawe** [nukeykt/NBlood#25]
Not sure if this is my issue or yours, latest master doesn't compile on Ubuntu 18.10:

> source/build/src/animvpx.cpp:15:10: fatal error: vpx/vpx_decoder.h: No such file or directory
>  #include <vpx/vpx_decoder.h>
>           ^~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Failed building obj/build/animvpx.o from source/build/src/animvpx.cpp!
> make: *** [GNUmakefile:1160: obj/build/animvpx.o] Error 1

**Comment by LiamDawe** [comment]
The problem was between the keyboard and the chair (me) woops, missing dependencies. Ignore me :+1:

**Comment by Mohit-Ak** [comment]
```sudo apt-get install -y libvpx-dev```
